### PR TITLE
Allow overriding config, add some common cPanel 'shortcuts'.

### PR DESCRIPTION
**Pull request by timgws**

### CODE REVIEW

**Comment by timgws** [comment]
Here is an example of using the cPanel shortcuts:

    $results = CpanelWhm::get('resller', 'topSecretPassword1234!one')
        ->listEmailAccounts('hosting');

    print_r(json_encode($results, JSON_PRETTY_PRINT));

    /**
      * Output:
      * -------------------
      *
      *    {
      *      "cpanelresult": {
      *        "apiversion": 2,
      *        "func": "listpops",
      *        "data": [
      *          {
      *            "email": "user@hosting.com",
      *            "login": "user@hosting.com"
      *          },
      *          {
      *            "email": "data@hosting.com",
      *            "login": "data@hosting.com"
      *          },
      *          {
      *            "email": "manyusers@hosting.com",
      *            "login": "manyusers@hosting.com"
      *          },
      *          {
      *            "email": "hosting",
      *            "login": "Main Account"
      *          }
      *        ],
      *        "event": {
      *          "result": 1
      *        },
      *        "module": "Email"
      *      }
      *    }
      *
      */

**Comment by timgws** [comment]
Ping @mgufrone =) any chance you could merge this pull request?

**Comment by mgufrone** [comment]
btw this package depends on https://github.com/mgufrone/cpanel-php. Your commits will be better to be merged to that package. :+1:

**Comment by timgws** [comment]
`CpanelShortcuts` has been moved to cpanel-php. I have created a new pull request (#6) for the cPanel specific stuff.

**Pull request closed without merging**
